# Generated by Django 5.2.5 on 2025-11-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterhunter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='element',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
