# Generated by Django 5.2.5 on 2025-11-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterhunter', '0002_monster_element_monster_name_monster_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='element',
            new_name='elements',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='type',
            new_name='species',
        ),
    ]
