# Generated by Django 5.2.5 on 2025-11-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterhunter', '0003_rename_element_monster_elements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rarity', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='monster',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonsterItemDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('chance', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterhunter.item')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterhunter.monster')),
            ],
        ),
    ]
