# Generated by Django 5.2.5 on 2025-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterhunter', '0004_item_alter_monster_image_url_monsteritemdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
