# Generated by Django 6.0 on 2025-12-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterhunter', '0005_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
